version: '3'
services:
  webapp:
    build: './webapp'
    ports:
      - "3000:3000"

  server:
    build: './server'
    ports:
      - "3003:3000"
    depends_on:
      - db
      - rd
    environment:
      - MONGO_DB_URI=mongodb://db/
      - REDIS_URL=redis://rd

  db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-pv:/data/db

  rd:
    image: redis
    ports:
      - "6379:6379"

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./webapp/public:/srv/www/static
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - server
      - webapp
volumes:
  mongo-pv:
